version: "3.8"

services:
  backend:
    build: .
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - .:/backend
    depends_on:
      - rabbitmq
      - redis
    command: /start-reload.sh

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - ./redis:/data

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./rabbitmq:/var/lib/rabbitmq



#  celery:
#    build: .
#    env_file:
#      - .env
#    command: celery -A app worker -l info
#    volumes:
#      - ./app:/app
